### PR TITLE
Added documentation from model tools onto script tools

### PR DESCRIPTION
**Pull request by BobBooth**
In the course of stripping away the models and exposing the scripts as
tools, the documentation for the tools got wiped out. I have copied the
content from the old tools into the script tools. Note that these two
toolboxes are not named the same as the toolboxes in the ArcMap docs or
Pro project.  They match the solutions-geoprocessing-toolbox naming
convention.

### CODE REVIEW

**Comment by BobBooth** [comment]
@mfunk or @topowright - edited the TBX files to fix the missing doc issue. Please review and merge.

**Comment by BobBooth** [comment]
@topowright - note that these toolboxes need to be merged into the ArcMap folder and added again to the Pro project.

**Comment by topowright** [comment]
This pull request is fixing the following issue: https://github.com/Esri/solutions-geoprocessing-toolbox/issues/574

**Comment by topowright** [comment]
This pull request looks good to merge. I have checked each of the three tools for tool help by opening the toolbox in ArcMap and clicking each of the input parameters to see if the tool help exist and makes sense. Here is the example in ArcMap: 
image

This is what the tool help looks like in Pro: 
image

**Comment by topowright** [comment]
This is the way the tool help looks when you hover over a parameter: 
image

**Comment by adgiles** [comment]
@topowright It looks like the GRG canvas area is set as optional this must be mandatory

**Pull request merged**
