### PR TITLE
Mf incident test parameter update

### PR DESCRIPTION
**Pull request by mfunk**
Corrected parameter order for Incident Analysis tools: Cluster Analysis and Count Incidents By LOC. Tests needed to be updated to match the changes.

## Description
For Cluster Analysis moved the optional Cluster Distance parameter from 2nd position to third (last) and updated test.
For Count Incidents By LOC moved the optional Search Distance parameter to the last position and updated test.

## Related Issue
N/A

## Motivation and Context
Following parameter order convention that makes it easier for script users to only use minimum number of parameters and not be forced to write out optional parameters.

## How Has This Been Tested?
Ran automated (unittest) tests for Incident Analysis tools to verify tests run successfully. The modified test are running, however there are errors in other tests.

```
Python 3.4 Tests ===============================
Debug messaging is OFF
Logging results to: SGT_2017-April-03_14-55-51_seq0.log
adding test: test_cluster_analysis_pro
adding test: test_count_incidents_pro
adding test: test_incident_density_pro
adding test: test_hot_spots_by_area_pro
adding test: test_incident_hot_spots_pro
adding test: test_incident_table_to_point_pro
adding test: test_percent_change_pro
running 7 tests...
...
...
...
Test success: False
RESULTS =================================================

Number of tests run: 7
Number of errors: 0
Number of failures: 3

FAILURES ===============================================

test_incident_density_pro (patterns_tests.IncidentDensityTestCase.IncidentDensityTestCase)Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\IncidentDensityTestCase.py", line 78, in test_incident_density_pro
    self.assertTrue(arcpy.Exists(outputDensity))
AssertionError: False is not true

test_incident_hot_spots_pro (patterns_tests.IncidentHotSpotsTestCase.IncidentHotSpotsTestCase)Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\IncidentHotSpotsTestCase.py", line 75, in test_incident_hot_spots_pro
    self.assertEqual(featureCount, int(7302))
AssertionError: 7286 != 7302

test_incident_table_to_point_pro (patterns_tests.IncidentTableToPointTestCase.IncidentTableToPointTestCase)Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\IncidentTableToPointTestCase.py", line 73, in test_incident_table_to_point_pro
    arcpy.IncidentTableToPoint_iaTools(self.inputTable, coordFormat, xField, yField, outputTable)
arcgisscripting.ExecuteError: ERROR 000576: Script associated with this tool does not exist.
Failed to execute (Add Unique Row ID).
Failed to execute (IncidentTableToPoint).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\IncidentTableToPointTestCase.py", line 76, in test_incident_table_to_point_pro
    self.fail('Exception in IncidentTableToPoint_iaTools for Pro toolbox \n' + msg)
AssertionError: Exception in IncidentTableToPoint_iaTools for Pro toolbox
ERROR 000576: Script associated with this tool does not exist.
Failed to execute (Add Unique Row ID).
Failed to execute (IncidentTableToPoint).



END OF TEST =========================================

Python 2.7 Tests ===============================
Debug messaging is OFF
Logging results to: SGT_2017-April-03_15-09-23_seq0.log
adding test: test_cluster_analysis_desktop
adding test: test_count_incidents_desktop
adding test: test_incident_density_desktop
adding test: test_hot_spots_by_area_desktop
adding test: test_incident_hot_spots_desktop
adding test: test_incident_table_to_point_desktop
adding test: test_percent_change_desktop
running 7 tests...
...
...
...
Test success: False
RESULTS =================================================

Number of tests run: 7
Number of errors: 0
Number of failures: 3

FAILURES ===============================================

test_hot_spots_by_area_desktop (patterns_tests.HotSpotsByAreaTestCase.HotSpotsByAreaTestCase)Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\HotSpotsByAreaTestCase.py", line 95, in test_hot_spots_by_area_desktop
    self.fail('Exception in HotSpotsByArea_iaTools for Desktop toolbox \n' + msg)
AssertionError: Exception in HotSpotsByArea_iaTools for Desktop toolbox


test_incident_table_to_point_desktop (patterns_tests.IncidentTableToPointTestCase.IncidentTableToPointTestCase)Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\IncidentTableToPointTestCase.py", line 96, in test_incident_table_to_point_desktop
    self.fail('Exception in IncidentTableToPoint_iaTools for Desktop toolbox \n' + msg)
AssertionError: Exception in IncidentTableToPoint_iaTools for Desktop toolbox
Failed to execute. Parameters are not valid.
ERROR 000816: The tool is not valid.
Failed to execute (IncidentTableToPoint).


test_percent_change_desktop (patterns_tests.FindPercentChangeTestCase.FindPercentChangeTestCase)Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\FindPercentChangeTestCase.py", line 94, in test_percent_change_desktop
    self.fail('Exception in FindPercentChange_iaTools for Desktop toolbox \n' + msg)
AssertionError: Exception in FindPercentChange_iaTools for Desktop toolbox
Failed to execute. Parameters are not valid.
ERROR 000725: Output Percent Change: Dataset C:\Users\<user>\AppData\Local\Temp\scratch.gdb\percentChange already exists.
Failed to execute (FindPercentChange).


END OF TEST =========================================

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Fatal Python error: PyEval_RestoreThread: NULL tstate

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

new problem tests are...
Pro:
- test_incident_density_pro
- test_incident_hot_spots_pro
- test_incident_table_to_point
Desktop:
- test_hot_spots_by_area_desktop
- test_incident_table_to_point_desktop
- test_percent_change_desktop

## Screenshots (if appropriate):
N/A

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X ] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by csmoore** [comment]
Changes look good but most/all the unit test failed (logs attached in case they help) - just let me know if this is a concern.

Failures seem related to `scratch = None` issue mentioned here: https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/206

[SGT_2017-April-04_07-59-30_seq0.zip](https://github.com/Esri/solutions-geoprocessing-toolbox/files/893070/SGT_2017-April-04_07-59-30_seq0.zip)

Also, this step/test takes 10 minutes which didn't seem quite right:  
Running tool (Count Incidents By LOC - Desktop)

**Comment by mfunk** [comment]
Looking at those logs you've got some really strange errors going on there. First any ideas why everything in is running from AppData\Local? Is this on your desktop? Also seeing a lot of errors pointing to output files like  ..\path\scratch.gdb\weirdname.shp.shp.shp which is a bad combo: File GDB + Shapefile.

**Comment by csmoore** [comment]
No idea - except they are all set to None here:
https://github.com/Esri/solutions-geoprocessing-toolbox/blob/mf-incident-test-parameter-update/utils/test/Configuration.py#L61 
I can debug further if you are also testing with this identical branch.

**Comment by mfunk** [comment]
So I'm a little lost. do we merge or not? I want to investigate your issues further, but don't want to keep these changes hanging. Suggestions?

**Comment by csmoore** [comment]
Merging - unit test failures can be new issue if desired

**Pull request merged**
