### PR TITLE
Adding Logic for missing attributes when user does not have a field to number for number features

### PR DESCRIPTION
**Pull request by topowright**
First commit covers the logic if a user have a new output feature class.

### CODE REVIEW

**Comment by topowright** [comment]
@mfunk the change in the tool box is switching the numbering field to optional

**Comment by mfunk** [comment]
@topowright 
in Number Features? Tool dialog in ArcMap has it as required:
image

image

**Comment by topowright** [comment]
@mfunk I think there is an issue because this is what I have:

**Comment by mfunk** [comment]
@topowright 
Downloaded directly from your branch on two different machines and see the same thing. Field To Number is still required. Did you make sure to sync your changes?

**Comment by topowright** [comment]
@mfunk I am not experiencing the same thing you are. I will take a closer look today.

**Comment by topowright** [comment]
Here is my update. I went in and changed the the input type and then changed in back to optional. 
image

**Comment by topowright** [comment]
This pull request addresses the following issues: 
https://github.com/Esri/solutions-geoprocessing-toolbox/issues/580
https://github.com/Esri/solutions-geoprocessing-toolbox/issues/574 (some of this has been done by @BobBooth )
https://github.com/Esri/solutions-geoprocessing-toolbox/issues/543

**Comment by mfunk** [comment]
Getting an error in ArcMap 10.3.1 when I run Number Features using the sample data from Clearing Ops template.

```
Executing: NumberFeatures "Feature Set" Structures Description D:\Workspace\scratch\nf0002.shp
Start Time: Thu Sep 07 08:05:27 2017
Running script NumberFeatures...
Shape type: Polygon
App environment: ARCMAP
Selecting points from (Structures) inside of the area ({870D4311-F65F-4A8C-8943-04FCA93F8705})
Selected 42 points
Sorting the selected points geographically, left to right, top to bottom
Numbering the fields
PYTHON ERRORS:
Traceback info:
  File "D:\GitHub\solutions-geoprocessing-toolbox\clearing_operations\scripts\NumberFeatures.py", line 149, in main
    row.setValue(numberingField, i)

Error Info:
ERROR 999999: Error executing function.
ArcPy ERRORS:
Executing: Sort Structures D:\Workspace\scratch\nf0002.shp "Shape ASCENDING" UR
Start Time: Thu Sep 07 08:05:27 2017
Succeeded at Thu Sep 07 08:05:27 2017 (Elapsed Time: 0.18 seconds)

Completed script NumberFeatures...
Failed to execute (NumberFeatures).
Failed at Thu Sep 07 08:05:28 2017 (Elapsed Time: 0.52 seconds)
```

Steps:
1) Open new map in ArcMap
2) Add Structures (points) and AO (polygons) from Clearing Ops template
3) Open Number Features from ClearingOperationsTools_arcmap.tbx
3a) Using Area_to_Number feature set tool, select points in eastern half of Structures
3b) Select Description as Field to Number
3c) Type output feature class name
4) Click OK

image

My guess is that ArcMap doesn't like the "Description" field to be the target field to be number, but the dialog still allows me to select it. If it is the case where the tool should only use numeric (Short, Long) fields to number the dialog should filter them:

image

**Comment by BobBooth** [comment]
@topowright - that doc issue we saw in your demo was not present in the TBX in my PR. 
@mfunk - once all this is merged I will retest the doc issues.

**Comment by mfunk** [comment]
@BobBooth not necessary, that's part of the review.

**Comment by mfunk** [comment]
@topowright 
Unfortunately #543 isn't fixed.

image

While the logic to add the field is in the script the filter logic in the validation will always cancel it out. 

image

**Comment by mfunk** [comment]
After talking with @topowright I'm understanding #543 isn't adding a user defined field, but an automatically generated field. If that is the case we are good and this is ready to go.

**Comment by mfunk** [comment]
@topowright Ok, merged. Please delete your branch for this PR.

**Comment by topowright** [comment]
[NumberedFeatures.zip](https://github.com/Esri/solutions-geoprocessing-toolbox/files/1304552/NumberedFeatures.zip)
@mfunk This is the most up to date layer file and lyrx file for Number Features. Please include this in your pull request.

**Comment by topowright** [comment]
@mfunk disregard my last message I will conduct the update in its own branch and pull request.

**Pull request merged**
