### PR TITLE
Merge unitest branch into dev

### PR DESCRIPTION
**Pull request by mfunk**
Merging unittest branch into dev. 
After this we will remove unittest branch.

### CODE REVIEW

**Comment by mfunk** [comment]
I'll be back in the office on 8/29/2016. If this isn't merged by then I'm going to merge it automagically.

**Comment by csmoore** [comment]
There are too many changes to review from the [PR page](https://github.com/Esri/solutions-geoprocessing-toolbox/pull/445/files) (I guess GitHub has a file/line limit).

But I was going to try to run the unittests, but am getting a few (repeated) errors:

So I may need some help figuring out my configuration issues - if you want me to test run:

```
Zip Name: MaritimeDecisionAidToolsTestData.zip
Extracting zip...
Deleting zip...
Downloaded MaritimeDecisionAidToolsTestData to C:\MyFiles\Work\Github\pr-test\solutions-geoprocessing-toolbox-unittest\utils\test\suitability_tests\data
Testing Visibility Range At Sea (Pro).
PYTHON ERRORS:
Traceback info:
  File "C:\MyFiles\Work\Github\pr-test\solutions-geoprocessing-toolbox-unittest\utils\test\suitability_tests\VisibilityRangeAtSeaTestCase.py", line 80, in test_visibility_range_at_sea
    arcpy.ImportToolbox(toolboxPath, "mdat")
```

```
test_GetProjectedPoint004 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\MyFiles\Work\Github\pr-test\solutions-geoprocessing-toolbox-unittest\utils\test\capability_tests\ERGScriptTestCase.py", line 185, in test_GetProjectedPoint004
    inputPoint = ERGTestUtils.getInputPointFCFromXY(-98.233824, 26.654716)
  File "C:\MyFiles\Work\Github\pr-test\solutions-geoprocessing-toolbox-unittest\utils\test\capability_tests\ERGTestUtils.py", line 53, in getInputPointFCFromXY
    sr)[0]
  File "C:\Users\Chris\AppData\Local\Programs\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1361, in CreateFeatureclass
    raise e
  File "C:\Users\Chris\AppData\Local\Programs\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1358, in CreateFeatureclass
    retval = convertArcObjectToPythonObject(gp.CreateFeatureclass_management(*gp_fixargs((out_path, out_name, geometry_type, template, has_m, has_z, spatial_reference, config_keyword, spatial_grid_1, spatial_grid_2, spatial_grid_3), True)))
  File "C:\Users\Chris\AppData\Local\Programs\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 500, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000258: Output in_memory\tempfc already exists
Failed to execute (CreateFeatureclass).
```

Note: I did try to go over the readme install steps, but a few of these steps don't seem to apply anymore (like getting submodules): https://github.com/Esri/solutions-geoprocessing-toolbox#fork-and-clone-the-repo

**Comment by mfunk** [comment]
The first one is Issue #403.
The second is #389.
So I guess at this point we will keep the branch open and continue to fix the test issues.

**Comment by mfunk** [comment]
... and the updated instructions should be in the README.md included in the PR, not the DEV branch, which is wrong.

**Comment by csmoore** [comment]
Updated instructions are there in unittest branch/fork now? Or will be there when the readme is updated? 

The configuration steps look the same to me: https://github.com/mfunk/solutions-geoprocessing-toolbox/blob/unittest/README.md#fork-and-clone-the-repo 

The step I didn't quite understand was the step/instructions to get submodules when they aren't any submodules.

**Comment by mfunk** [comment]
Removed the lines mentioning submodules from the README.md

**Pull request merged**
