### PR TITLE
Fix Incident Analysis Test Errors

### PR DESCRIPTION
**Pull request by csmoore**
Fix Incident Analysis Test Errors - https://github.com/Esri/solutions-geoprocessing-toolbox/issues?q=is%3Aopen+is%3Aissue+label%3A%22unit+test%22+label%3A%22N+-+Incident+Analysis%22

See:

#476 #477 #478 #479 #515 

**IMPORTANT NOTE** 2 of the tests (ClusterAnalysisTestCase, IncidentDensityTestCase) will still fail in Pro until Issue #559 is resolved. I tested this by working around this issue by copying the "layers" folder to "layerfile" folder in same directory

# How Has This Been Tested?

Unit Test Runner

**IMPORTANT NOTE** 2 of the tests (ClusterAnalysisTestCase, IncidentDensityTestCase) will still fail in Pro until Issue #559 is resolved. I tested this by working around this issue by copying the "layers" folder to "layerfile" folder in same directory

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by csmoore** [comment]
This is ready to re-test/review after merging #565

**Comment by csmoore** [comment]
Note this will have a merge conflict with #569 - I will resolve after that is merged

**Comment by mfunk** [comment]
@csmoore Just ran this one and Pro is looking good:
```
Python 3.4 Tests ================================
TestRunner.py
TestRunner.py - main
UnitTestUtilities - getLoggerName
...
...
...
RESULTS =================================================
Number of tests run: 9
Number succeeded: 8
Number of errors: 0
Number of failures: 1
Number of tests skipped: 0
Percent passing: 88.9
=========================================================

FAILURES ================================================
test_sun_position_analysis (sun_position_analysis_tests.SunPositionAndHillshadeTestCase.SunPositionAndHillshadeTestCase)
Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\sun_position_analysis_tests\SunPositionAndHillshadeTestCase.py", line 129, in test_sun_position_analysis
    self.assertEqual(rasMaximum, float(0))
AssertionError: -2.0 != 0.0
END OF TEST =========================================
```

... but getting an error in 2.7/ArcMap that i'm not sure is related.


```
Python 2.7 Tests ================================
TestRunner.py
TestRunner.py - main
UnitTestUtilities - getLoggerName
...
...
...
Test success: False

RESULTS =================================================
Number of tests run: 9
Number succeeded: 8
Number of errors: 0
Number of failures: 1
Number of tests skipped: 0
Percent passing: 0.0
=========================================================

FAILURES ================================================
test_count_incidents (incident_analysis_tests.CountIncidentsByLOCTestCase.CountIncidentsByLOCTestCase)
Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\incident_analysis_tests\CountIncidentsByLOCTestCase.py", line 130, in test_count_incidents
    self.assertFeatureClassEqual(self.resultCompareFeatures0001, outputCountFeatures, "OBJECTID")
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\arcpyAssert.py", line 109, in assertFeatureClassEqual
    raise AssertionError(msg)
AssertionError: Feature class D:\GitHub\solutions-geoprocessing-toolbox\utils\test\test_data\incident_analysis\test_incident_analysis_results.gdb\outputCount is not equal to D:\GitHub\solutions-geoprocessing-toolbox\utils\test\test_data\incident_analysis\test_incident_analysis_results.gdb\resultsCountIncidentsByLOC_0001
END OF TEST =========================================
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Fatal Python error: PyEval_RestoreThread: NULL tstate

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
'One or more tests failed'
```

**Comment by csmoore** [comment]
@mfunk - thanks for testing - this should be good to review/merge now

Note: I wasn't expecting that Incident Test Failure in 10.X shown above - so you may have to delete your `test_data\incident_analysis` folder and retest - since I did update the testdata/expected results download. I guess this is an issue with the current data fetch, that we may need to add a mechanism for refetching if the download changes (like keep the zip and compare the zip sizes)

**Comment by csmoore** [comment]
@mfunk - addressed the last failing Pro test (sun position in Pro test output above) in #570 

After (1) these 2 PRs and (2) deleting and refetching your `test_data` folder all tests should pass now on both platforms

**Comment by mfunk** [comment]
Looks good in Pro, and Desktop is only flaking on Sun Position for the moment..

```
D:\GitHub\solutions-geoprocessing-toolbox\utils\test [csm/incident-tests-errors ≡]> .\TestKickPro.bat
Python 3.4 Tests ================================
TestRunner.py
TestRunner.py - main
UnitTestUtilities - getLoggerName
...
...
...
RESULTS =================================================
Number of tests run: 12
Number succeeded: 11
Number of errors: 1
Number of failures: 0
Number of tests skipped: 0
Percent passing: 91.7
=========================================================

ERRORS ==================================================
test_sun_position_analysis (sun_position_analysis_tests.SunPositionAndHillshadeTestCase.SunPositionAndHillshadeTestCase)
Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\sun_position_analysis_tests\SunPositionAndHillshadeTestCase.py", line 72, in setUp
    self.compareResults])
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 174, in checkGeoObjects
    desc = arcpy.Describe(object2Check)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 1223, in Describe
    return gp.describe(value)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 368, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
OSError: "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\test_data\sun_position_analysis\test_sun_position.gdb\compareResults" does not exist
END OF TEST =========================================
'One or more tests failed'
```

```
D:\GitHub\solutions-geoprocessing-toolbox\utils\test [csm/incident-tests-errors ≡]> .\TestKickDesktop.bat
Python 2.7 Tests ================================
TestRunner.py
TestRunner.py - main
UnitTestUtilities - getLoggerName
UnitTestUtilities - initializeLogger
...
...
...
RESULTS =================================================
Number of tests run: 12
Number succeeded: 11
Number of errors: 1
Number of failures: 0
Number of tests skipped: 0
Percent passing: 0.0
=========================================================

ERRORS ==================================================
test_sun_position_analysis (sun_position_analysis_tests.SunPositionAndHillshadeTestCase.SunPositionAndHillshadeTestCase)
Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\sun_position_analysis_tests\SunPositionAndHillshadeTestCase.py", line 72, in setUp
    self.compareResults])
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 174, in checkGeoObjects
    desc = arcpy.Describe(object2Check)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\__init__.py", line 1246, in Describe
    return gp.describe(value)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\geoprocessing\_base.py", line 374, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
IOError: "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\test_data\sun_position_analysis\test_sun_position.gdb\compareResults" does not exist
END OF TEST =========================================
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\matplotlib\_pylab_helpers.py", line 84, in destroy_all
    for manager in Gcf.figs.values():
AttributeError: 'NoneType' object has no attribute 'figs'
Fatal Python error: PyEval_RestoreThread: NULL tstate

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
'One or more tests failed'
```

**Comment by csmoore** [comment]
@mfunk - hopefully it isn't our testrunner that is crashing your python at 10.3 in your output above (I have not seen this)

**Pull request merged**
