### PR TITLE
Fixing #483 - Incident Density now respects layer definition queries

### LINKED ISSUE #483: Incident Density does not respect layer definition queries
Run the Incident Density tool on the last 30 days layer.  
Now run the Incident Density tool on the month before last layer.
The results are the same.
Compare this to running the Buffer tool on the same two layers. Buffer respects the definition query, Incident Density does not.

## Expected Behavior
I would expect the tool to respect the definition query on the layer.

## Your Environment
Incident Analysis 4.0.1 - ArcMap 10.5.0

### PR DESCRIPTION
**Pull request by Dbarnes1**
@mfunk @BobBooth based on what we went over today I added the Copy Features tool to the models for ArcMap and ArcGIS Pro because the Project tool (the next one in the model) doesn't honor layer definition queries. Once this PR is merged @kgonzago can open his PR for fixing the unit tests in these .tbx files. 

Fixes #483

### CODE REVIEW

**Comment by BobBooth** [comment]
@Dbarnes1 - I grabbed the ArcMap tbx. It is failing for me with:
ERROR 000208: Error creating output feature class
Failed to execute (Project Incident Boundaries).
Failed at Thu Jul 27 14:46:45 2017 (Elapsed Time: 0.13 seconds)
Failed to execute (IncidentDensity).

-=-
The output dataset for both of the Project tools is pointing to:
C:\ArcGIS\Default.gdb\
which doesn't exist on my system.
In mine Project is pointing to:
%ScratchGDB%\Incidents_Project

**Comment by BobBooth** [comment]
Might also be clearer to reorg the model layout:
image

**Comment by BobBooth** [comment]
If I update the paths of the project tools in the model to
%ScratchGDB%\Incidents_Project
%ScratchGDB%\Boundaries_Project
it works.

**Comment by Dbarnes1** [comment]
@BobBooth good catch. I think the fix I made works now

**Comment by mfunk** [comment]
Hey @BobBooth, Dan assigned you as reviewer, do you have time to check it out?

**Comment by BobBooth** [comment]
@mfunk - struggling with the Compound Map stuff at the moment - if you could take it, that would be great.

**Comment by Dbarnes1** [comment]
@csmoore if you have time could you review this as well?

**Comment by csmoore** [comment]
@Dbarnes1 - sure - will try it out in a bit

**Comment by csmoore** [comment]
Reviewed/verified with #483 

I noticed a small naming difference between the template toolboxes & these files in that the template toolbox versions don't have "_arcmap" "_pro" - just let me know if this is an issue

**Comment by csmoore** [comment]
Regarding naming - just saw @mfunk 's comment: https://github.com/Esri/solutions-geoprocessing-toolbox/issues/533#issuecomment-319427468 -  `We've discussed this in meetings that the toolbox MAY be renamed when 'added' to the output template, be it Pro or Desktop, or it may stay the same (with _arcmap or _pro). `  -  so please disregard

**Pull request merged**
