### PR TITLE
Add Compound Map toolbox, scripts, lyrx

### PR DESCRIPTION
**Pull request by BobBooth**
This is an attempt to add the Compound Map_pro toolbox, with scripts and
LYRX file in the configuration that actually works in a pro project.

### CODE REVIEW

**Comment by BobBooth** [comment]
@mfunk  - this is the toolbox, two scripts, and LYRX file (in two locations) for compound map to work when added to a new Pro project.
Note - no data included. Requires a point feature class with a field called "Number" of type "short" to store the numbers.

**Comment by adgiles** [comment]
Bob I am already uploading the scripts as part of the clearing operations. Your number features script looks different, we had to change the way the lyrx file was applied as it does not honour the  label styles unless you use the apply style to layer  gp tool within the application, that's why we added the task step to do this. You may not be noticing this if your are just using the default label style.

**Comment by mfunk** [comment]
@BobBooth lets close this one and wait for @adgiles to finish up Clearing Operations.

**Comment by BobBooth** [comment]
@mfunk  - OK. I was trying to match the structure in a deployed project, built from a template. Happy to hold on and see what @adgiles does.

**Pull request closed without merging**
