### PR TITLE
fix #557 by reordering script tool parameters

### LINKED ISSUE #557: Clearing Operations Point target GRG failing
ExecuteError: Executing: CopyFeatures in_memory\tempSort Alpha-Numeric # 0 0 0
Start Time: Fri Aug 04 09:38:47 2017
ERROR 000210: Cannot create output Alpha-Numeric
Failed to execute (CopyFeatures).
Failed at Fri Aug 04 09:38:47 2017 (Elapsed Time: 0.02 seconds)
Failed to execute (Point Target GRG Script).
Failed to execute (PointTargetGRG).

Tool failing to execute. Error I'm receiving above.

### PR DESCRIPTION
**Pull request by mfunk**
## Description
Reorder the script tool parameters in Pro and Desktop to match the
script as follows:
```
targetPointOrigin = arcpy.GetParameterAsText(0)
numberCellsHo = arcpy.GetParameterAsText(1)
numberCellsVert = arcpy.GetParameterAsText(2)
cellWidth = arcpy.GetParameterAsText(3)
cellHeight = arcpy.GetParameterAsText(4)
cellUnits = arcpy.GetParameterAsText(5)
gridSize = arcpy.GetParameterAsText(6)
labelStartPos = arcpy.GetParameterAsText(7)
labelStyle = arcpy.GetParameterAsText(8)
outputFeatureClass = arcpy.GetParameterAsText(9)
```

## Related Issue
#557 

## Motivation and Context
Fixes bug in tool's parameter order which casues tool to fail.

## How Has This Been Tested?
Manual test
Automated tests are part of #556 

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by csmoore** [comment]
There may be an error in the PointGRG Model in this PR:

image

I get this if I try to run:

image

**Comment by csmoore** [comment]
Looks like quite a few of the model parameters were mis-set in the ArcMap model, fixing these mismapped parameters seems to get things to work again:

image

**Comment by csmoore** [comment]
And it looks like the tbx version that @pHill5136 did in #556 fixes this:

image

So I guess I have the answer to my question in https://github.com/Esri/solutions-geoprocessing-toolbox/pull/556#issuecomment-321002741

**Comment by mfunk** [comment]
I reordered all three in this PR. Can't say what happened. I'm in the middle of another fix and can't switch branches at the moment.

**Comment by csmoore** [comment]
I put the work versions of these 2 branches together in https://github.com/Esri/solutions-geoprocessing-toolbox/tree/csm/fix-clearing-ops-PR - may want to cancel these 2 PRs and just go with that one

**Comment by mfunk** [comment]
This is weird. I switch back to my branch for this PR and the parameters match between the script, the script tool and the model.....
image
image

**Comment by csmoore** [comment]
@mfunk - it was the actual model process that had the mismatched parameters in this PR:

image

**Comment by csmoore** [comment]
I'm also have problem using the Pro tbx version but don't know how to fix since I can't view the model steps - which is the same corrupt behavior I saw with the pro Geonames in #547 :

image

image

**Comment by mfunk** [comment]
@csmoore try this one. Reset paths in models for Desktop and Pro. If this doesn't work, I need to either completely wipe my machine and start over, or fine another line of GIS work.

**Comment by csmoore** [comment]
This review seems cursed:

image

**Comment by mfunk** [comment]
dang it. Found a tab/space mix in .PY. I'm able to run the tool in Pro and in Desktop on my machine, which is pretty much worthless.

**Comment by mfunk** [comment]
@csmoore try it one more time after the last commit.

**Comment by csmoore** [comment]
I can now run the tool, but I actually have to clear the Grid Size parameter to get it to run - is that the intended behavior?  In ArcMap it just ignores it and no need to clear

image

**Comment by mfunk** [comment]
@csmoore I did not have that problem in Pro

image

**Comment by csmoore** [comment]
Looks the same (except point is map layer above) - perhaps try with the `test_data` dataset:

On Pro 1.4:
image

**Comment by adgiles** [comment]
In pro 2.0 the user has the ability to draw a grid size using the polygon tool, they will not have this option in 1.4 so in_memory\feature_set does not exist

**Comment by csmoore** [comment]
I am able to open the model step - so not sure how the previous pro version was corrupted but the new one works better:

image

**Comment by mfunk** [comment]
I'm using this on Pro 1.4 :
image

I'm setting the grid option is set by size and units rather than sketching. Any idea why @csmoore is seeing it differently?

**Comment by adgiles** [comment]
not sure then?

maybe daft, but could it be anything to do with dark mode vs light mode

**Comment by mfunk** [comment]
Or just the whole thing is crap. Second time trying to run the tools fails...

image

**Comment by mfunk** [comment]
and this is new...
image

**Comment by csmoore** [comment]
@mfunk - I did not have that problem running multiple times (but was running with GridSize=#/null)

**Comment by mfunk** [comment]
@csmoore Unfortunately clearing it does not fix the "Tool is not valid" error. 
image

Which is dumb because I can still access the script tool dialog within the model:
image

**Comment by mfunk** [comment]
After restarting Pro it works again...
image
.. and a second time with same inputs.
.. and a third time.
I think  I need to wipe Pro and reinstall. I don't get it.

**Comment by csmoore** [comment]
We can call Point GRG good in Pro but the other 2 Pro tools are showing the corruption problem:

image

**Comment by mfunk** [comment]
Continuing to uncurse the cursed PR I've added another commit that rebuilt the links to the script tools in the models for Number Features and Canvas Area GRG.
I also found a tab/space in the CanvasAreaGRG.py script also and fixed that in this commit.
@csmoore lets try this again.....perhaps one more time and it might actually work.

**Comment by csmoore** [comment]
Tests in #569 ran clean in Pro 1.4 and model step can be viewedopened now.

Only one minor thing I noticed (that can be opened in new issue if it is in fact an issue) is the default parameter gives a warning (but this doesn't affect the tool's function once set)

image

Merging before any other bad juju can happen

**Comment by mfunk** [comment]
@csmoore Yes. If you are running that tool outside of the template you will always have that error as you figured out. I don't like the idea of having layer-based defaults in tools, but in the end they're going to do it anyway.

**Pull request merged**
