### PR TITLE
Changes to get Patrol Data Capture Toolbox to work in Pro

### PR DESCRIPTION
**Pull request by csmoore**
Changes to get Patrol Data Capture Toolbox to work in Pro and ArcMap/ArcToolbox 10.X. Tested Toolbox with Pro 1.0 and ArcMap 10.1.

Specifically changes, made tabs consistent, changed cursors (added fields, changed to da.cursor where possible), added some Pro-specific workarounds.

### CODE REVIEW

**Comment by mfunk** [comment]
@csmoore So is the TBX 'updated' for Pro? If so we need to have a 10.3 version (as Pro toolboxes are not backwards compatible).

**Comment by csmoore** [comment]
This same .tbx works in 10.X and Pro (i.e. I used the 10.X version in Pro unmodified)

**Comment by mfunk** [comment]
.... and tested in 10.x after using in Pro? I'm asking  because I'm going to be duplicating most of the toolboxes for 10.3 and Pro.

**Comment by csmoore** [comment]
Tested in 10.X - there is no Pro-specific version, it has never been saved in Pro (but does work unmodified in Pro - that is the hope anyway)

**Comment by mfunk** [comment]
Just need to get the changes in before I finish this duplication. Thanks.

**Pull request merged**
