### PR TITLE
Added Compound Map Tools to repo

### PR DESCRIPTION
**Pull request by mfunk**
Added _pro.tbx and _arcmap.tbx to repo and updated README.MD.
Fix for #519 

## Description
- Added Compound Map Tools_arcmap.tbx and Compound Map Tools.pro.tbx to *clearing_operations* folder.
- Made updates to README.MD identifying which toolboxes are included and link to the solutions page.

## Related Issue
#519 

## Motivation and Context
Now tracking changes to Compound Map in this repo.
Eventually we will probably want to rename the folder from *clearing_operations* to something like *clearing_ops_and_compound_map*.

## How Has This Been Tested?
Manual tested.
Automated tests to be added in later with a new Issue: #539 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by topowright** [comment]
@mfunk @BobBooth @adgiles I have a fear that the updates that @adgiles and myself did are not the same that are in this pull request. I was under the impression that we were going to update our changes after this body of work. I understand how this can be wrong, but I think we should hold off on this to make sure @adgiles and my changes are also captured.

**Comment by BobBooth** [comment]
@mfunk @BobBooth @adgiles @topowright - I'm with Lyle on this. Lyle and I both did a lot of tweaking of the toolbox for Pro to get it to package. Gigzy changed the Py scripts for symbology. Want to make sure wa have the latest and greatest.

**Comment by mfunk** [comment]
@topowright @BobBooth @adgiles 
We need to get those changes into the repo. If we are making changes in the templates and the download page is the only way we are maintaining changes to toolboxes...

**Comment by mfunk** [comment]
@topowright @BobBooth @adgiles 
Actually this is the perfect time to do it since the "latest and greatest" lives somewhere else (?!?) and not in the repo this is the perfect time to get those changes into the repo.

**Comment by BobBooth** [comment]
@topowright @BobBooth @adgiles @mfunk 
OK, prepping Pro version for you. Note, will have to add a "commondata\userdata" folder to the repo to store the NumberedStructures.lyrx file, and take the "NumberFeatures.py" and "Utilities.py" scripts out of the scripts folder and put them at the same level as the toolbox -- that's just how it has to be in order to work in the Pro project template package/unpackage process.

**Comment by mfunk** [comment]
@BobBooth 
Closing this PR. Please make changes in a new one.

@topowright @adgiles

**Pull request closed without merging**
