### PR TITLE
Support for latest geonames schema & Python 3.x

### PR DESCRIPTION
**Pull request by elinz**
- Modified scripts to support NGA geonames text file schema that existed
on NGA geonames web site on 29 March 2016.
- Modified scripts to execute in ArcMap and ArcGIS Pro (i.e. Python 2.x
and 3.x)
- Modified Load Geonames File model to use Python_9.3 instead of VB in
Calculate Field tool.
- Created "Geonames Tools.tbx" for use in ArcGIS Pro by copying the "Geonames Tools_10.4.tbx" file.

### CODE REVIEW

**Comment by mfunk** [comment]
@elinz Got issue:

Open **Create Geonames Gazetter Locator** and there's a path in the *Output Geonames Gazetteer Locator* parameter that points to: *C:\Users\<your_user_name>\AppData\Local\Temp\arcC12A\GeonamesAA_CreateAddressLoca*, where <your_user_name> is actually pointing to your own user name. Might want to send it to %scratchGDB% as a default.

**Comment by elinz** [comment]
@mfunk ArcMap supports creating address locators in both a folder and a geodatabase, however, ArcGIS Pro only allows creation in a folder so I wouldn't want to set this path to the %scratchGDB%.

**Comment by mfunk** [comment]
@elinz Then it should use %scratchFolder%. Either way we need to remove your username.

**Comment by elinz** [comment]
@mfunk Oops. I didn't realize that was hardcoding the user name. Thanks. I'll change.

**Comment by elinz** [comment]
@mfunk Modified the Create Address Locator tool in Geonames Tools_10.4tbx; copied this file to re-create the Geonames Tools.tbx for use in ArcGIS Pro.

**Pull request merged**
