### PR TITLE
Updates to Clearing Operations and Compound Map

### PR DESCRIPTION
**Pull request by topowright**
Action taken:
changed the script to rely on the script tool to set the symbology and
labels.
Note:
Based on best practices coming from the gp core team I have commented
out the steps that apply symbology in the script and set the script tool
to look at the layer file.

### CODE REVIEW

**Comment by topowright** [comment]
More commits coming please do not merge yet.

**Comment by adgiles** [comment]
Why are you changing the arcmap functionality when it works exactly as it should?

**Comment by topowright** [comment]
@adgiles going with the approach that we currently had was not matching up with what the gp team gave us for feedback. Also, it did not produce the results with labels in the correct place. Now that we have applied the advice that they have given us the script tool symbolizes and labels correctly. This was why we took this approach.  Going forward it could be useful to have all our script tools drive symbology unless that is not possible based a more complex workflow such as dealing with adding group layers to the ToC.

**Comment by adgiles** [comment]
Can the symbology task steps be removed from pro then?

**Comment by topowright** [comment]
I am finished with my commits and this can now be reviewed

**Comment by topowright** [comment]
@adgiles unfortunately not because this is still a bug in ArcGIS Pro 2.0. I have explained to them that we are seeing the same results; however, we will be ready for ArcGIS Pro 2.1 when they make those changes.

**Comment by mfunk** [comment]
@topowright 
* Desktop 10.3.1 is good.
* Desktop 10.5 is good.
* Pro 1.4 is still giving me bad models (GitHub screwing with things?):
image

Script tool is running without errors, but is not picking up the LYRX stored in the Script Tool parameters. No symbols, no layers.
😠 

* Pro 2.0 also has a bad Number Features model (still GitHub?). But the Number Features Script tool will run and use the LYRX (but no labels.... yet).
image

**Comment by mfunk** [comment]
@topowright I'm noticing that I can't add the NumberedStructures.lyrx to my map directly. It should be added with a broken data link at least. Wasn't sure why until I cracked it open:

```
{
  "type" : "CIMLayerDocument",
  "version" : "2.0.0",
  "build" : 8933,
  "layers" : [
    "CIMPATH=clearing_operations/numberedstructuressample.xml"
  ],
  "layerDefinitions" : [
    {
```

So a version 2.0 LYRX won't work in 1.4. 
Was able to add the NumberedStructure.lyr to my may but got an interesting layer name int he doc...
image

We need to rename that guy in ArcMap 10.3.1.
Now if I export the .LYR to a new .LYRX in 1.4 ...

```
{
  "type" : "CIMLayerDocument",
  "version" : "1.4.0",
  "build" : 7198,
  "layers" : [
    "CIMPATH=map/asdfasde.xml"
  ],
  "layerDefinitions" : [
```
HA!!!! VERSION SPECIFIC LAYERS!!!!!!!!!!!
The modified 1.4 LYRX symbolizes nicely in 1.4 then...

image

**Comment by topowright** [comment]
The script tool not working with Kurd file is a known bug in Pro. I have replicated it on 2.1 as well. The script losing its link is also another known issue logged with the go code team. I did no work in ArcGIS Pro 1.4 only 2.0 and 2.1

**Comment by topowright** [comment]
I am working right now on creating a lyrx file in 1.4. I did not have a 1.4 system set up because I did not think we were doing this. I will push the new lyrx file soon as I finish.

**Comment by topowright** [comment]
@mfunk I have added the lyrx files created in ArcGIS Pro

**Comment by mfunk** [comment]
Good. Good. Good. **Number Features Script** tool is showing yellow block (no labels) in Pro 1.4 now
image

Same in Pro 2.0, got yellow blocks (no labels).

**Pull request merged**
