### PR TITLE
Added Number Features lyr and lyrx files

### PR DESCRIPTION
**Pull request by topowright**
Added the updated lyr and lyrx files to the repo for updates to Number Features tool. The new layer files now incorprate both workflows from Compound Map and Clearing Operations.

### CODE REVIEW

**Comment by topowright** [comment]
Pull request addresses: 
https://github.com/ArcGIS/solutions-defense/issues/403

https://github.com/Esri/solutions-geoprocessing-toolbox/issues/543

**Comment by topowright** [comment]
@BobBooth could you please review this pull request.

**Comment by BobBooth** [comment]
@mfunk  - please merge.

**Comment by topowright** [comment]
@BobBooth Thanks

**Pull request merged**
