### PR TITLE
Set output to None if no output param given #607

### PR DESCRIPTION
**Pull request by csmoore**
See #607

## Description

See #607

## How Has This Been Tested?

Unit Tests (also updated these to add test case for #607)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by topowright** [comment]
@csmoore I am testing the tool on ArcMap 10.3.1 and I have received the following error: 
image
'''
Executing: NumberFeatures "Feature Set" TestsOne # C:\Users\lyle6003\Documents\ArcGIS\Default.gdb\Test
Start Time: Mon Sep 25 14:08:20 2017
Running script NumberFeatures...

Traceback (most recent call last):
  File "C:\Users\lyle6003\Documents\GitHub\solutions-geoprocessing-toolbox\clearing_operations\scripts\NumberFeaturesTool.py", line 120, in execute
    parameters[3].value)
  File "C:\Users\lyle6003\Documents\GitHub\solutions-geoprocessing-toolbox\clearing_operations\scripts\NumberFeaturesTool.py", line 131, in NumberFeatures
    descPointFeatures = arcpy.Describe(pointFeatures)
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\__init__.py", line 1246, in Describe
    return gp.describe(value)
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\geoprocessing\_base.py", line 374, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
RuntimeError: Object: Describe input value is not valid type

Failed to execute (NumberFeatures).
Failed at Mon Sep 25 14:08:20 2017 (Elapsed Time: 0.06 seconds)
'''

**Comment by topowright** [comment]
I was not able to reproduce the error more than once. I have now run the tool more than 10 times with these inputs and had no problem.

**Comment by topowright** [comment]
Everything looks good. Merging this pull request.

**Comment by csmoore** [comment]
@topowright - Thanks for testing - that error above does concern me - the only thing I can think of that would cause that is if it is not a valid input FeatureClass - so perhaps an arcpy.exists could be added first

**Comment by topowright** [comment]
@csmoore I was only able to replicated the fail twice then it worked fine. I ran the tool multiple time and see if I could get it to fail, but had no luck

**Pull request merged**
