### PR TITLE
Added MDCS submodule to repo

### PR DESCRIPTION
**Pull request by mfunk**
Added MDCS (Esri/mdcs-py) as a submodule to repo.
@csmoore would you be able to test this one out and see if it make sense? Instructions are included in the data_management\README.md and also some additional (more generic) in the main README.md.

### CODE REVIEW

**Comment by csmoore** [comment]
Sure, I can give it a test

**Comment by csmoore** [comment]
Tested the .bat & only one file/folder didn't create, get copied (noted above & [here](https://github.com/mfunk/solutions-geoprocessing-toolbox/commit/5924972815cdc8897e40a89cfb07daf52be1e994#commitcomment-9995114) )

Here is the bad output:

Copying CIB Tools config files...
The system cannot find the path specified.
        0 file(s) copied.

**Comment by csmoore** [comment]
Only other comment would be to add a "Credits" section to the main repo readme with a link to the MDCS repo & license (even though we know it is Esri and Apache - just a general good practice to provide credit/license)

**Comment by mfunk** [comment]
@csmoore Some updates.

**Comment by csmoore** [comment]
Copy steps work now, however I couldn't get the data_management tests to run in order to verify things are working as expected.

But not sure if these tests are currently working or not - just let me know if I should merge. I do see a lot of test-related issues, but don't see one related to this: https://github.com/Esri/solutions-geoprocessing-toolbox/search?q=test&state=open&type=Issues

Here was the output:

```
test_build_elevation_mosaic:
     [exec] scratch.gdb already exists
     [exec] Starting Test: Build Elevation Mosaic Tools
     [exec] ERROR: Executing: BuildElevationMosaics C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_manage
ment\data\geodatabases\scratch.gdb C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\data\Topographic\Elevation\Source DTED "C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\toolboxes\Raster Functions\10.3\AspectNumericValues.rft.xml" "C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\tool
boxes\Raster Functions\10.3\SlopePercentRise.rft.xml" "C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\toolboxes\Raster Functions\10.3\GreyScaleHillshade.rft.xml" DigitalTerrainModel C:\Users\chri0020\github\solutio
ns-geoprocessing-toolbox\data_management\data\geodatabases\scratch.gdb\Hillshade C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\data\geodatabases\scratch.gdb\Aspect C:\Users\chri0020\github\solutions-geoprocessing-
toolbox\data_management\data\geodatabases\scratch.gdb\PercentSlope
     [exec] Start Time: Tue Mar 03 05:42:08 2015
     [exec] Failed to execute. Parameters are not valid.
     [exec] ERROR 000732: Mosaic Dataset: Dataset C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\data\geodatabases\scratch.gdb\DigitalTerrainModel does not exist or is not supported
     [exec] Failed to execute (BuildElevationMosaics).
     [exec] Failed at Tue Mar 03 05:42:10 2015 (Elapsed Time: 1.73 seconds)
     [exec] Executing: BuildElevationMosaics C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\data\geodatabases\scratch.gdb C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\data\Topographic\Elevation\Source DTED "C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\toolboxes\Raster Functions\10.3\AspectNumericValues.rft.xml" "C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\toolboxes\Raster Functions\10.3\SlopePercentRise.rft.xml" "C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\toolboxes\Raster Functions\10.3\GreyScaleHillshade.rft.xml" DigitalTerrainModel C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\data\geodatabases\scratch.gdb\Hillshade C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\data\geodatabases\scratch.gdb\Aspect C:\Users\chri0020\github\solutions-geoprocessing-toolbox
\data_management\data\geodatabases\scratch.gdb\PercentSlope
     [exec] Start Time: Tue Mar 03 05:42:08 2015
     [exec] Failed to execute. Parameters are not valid.
     [exec] ERROR 000732: Mosaic Dataset: Dataset C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_manageme
nt\data\geodatabases\scratch.gdb\DigitalTerrainModel does not exist or is not supported
     [exec] Failed to execute (BuildElevationMosaics).
     [exec] Failed at Tue Mar 03 05:42:10 2015 (Elapsed Time: 1.73 seconds)

BUILD FAILED
C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\test\build.xml:30: The following error occurred
 while executing this line:
C:\Users\chri0020\github\solutions-geoprocessing-toolbox\data_management\test\test_build_elevation\build.xml:26: exec returned: -1
```

**Comment by mfunk** [comment]
@csmoore @NatalieCampos @abhiataero just updated the header myself. Included our 'standard' license header as well.

**Comment by csmoore** [comment]
OK I can merge this now since [the test driver issue](https://github.com/Esri/solutions-geoprocessing-toolbox/pull/228#issuecomment-76948830) isn't likely related to these changes - since I don't think the new .pyts have tests - do you want me to add a new issues for these: (1) broken test driver (2) missing test driver?

**Comment by mfunk** [comment]
Yes. please add both.

**Comment by csmoore** [comment]
Ancillary issues noted in #229 and #230

**Comment by NatalieCampos** [comment]
I am unable to run the tools.  this is what I did

1. clones the repo
2. added the correct .pyt files, .xml, 
3.  Add the folder to pro and attempted to run tools.  Toolboxes are there but are empty.
image


Next I 

1.  replaced the parameter folder and the scripts folder in the MDCS-py folder with the folders I have and the result is the same.  No tools in the tools folder.  
@abhiataero @mfunk

**Comment by csmoore** [comment]
@NatalieCampos - just to verify, you also did the setup steps at 

https://github.com/Esri/solutions-geoprocessing-toolbox/blob/master/data_management/README.md#setting-up-mdcs-py

(I only tested this on 10.X, but I could at least open the toolboxes/tools there)

**Comment by mfunk** [comment]
The PYTs were already in the repo. You gave them to me on 2/26. Perhaps you should roll back your toolbox commits and check again? What made the ones you gave me wrong? Did you make changes since then?

**Comment by mfunk** [comment]
Scratch that. @NatalieCampos  So did the original tools work in Pro? I was able to see them.

image


The tools were the ones you sent to me on 2/26. If you made changes to the PYTs you might want to go back and check your edits first.

@csmoore were you able to see and use the tools in Pro?

**Comment by csmoore** [comment]
They opened in Pro for me

image

**Pull request merged**
