### PR TITLE
Removed steps in the Table to Point model that are not need

### PR DESCRIPTION
**Pull request by topowright**
The model has not been updated since ArcGIS for Desktop 10.1. At that
point the Convert Coordinate Notation GP tool did not keep the
attributes. Due to this there was a py script that was needed to add
unique ids to table and a join step to get your final output.

This is not needed anymore as of ArcGIS for Desktop 10.2

### CODE REVIEW

**Comment by dfoll** [comment]
That makes that step just Convert Coordinate Notation, correct? Should we just be getting rid of Incident Table to Point then?

**Comment by mfunk** [comment]
@topowright Can you update the Pro toolbox as well?

**Comment by topowright** [comment]
There is a known issue with 1.3 with this tool. This tool will not have drop down menus in 1.2 if there are edits made. This fix was only for ArcMap

**Comment by mfunk** [comment]
!@#$%
OK. For ArcMap only. and a known issue for Pro. :smiling_imp: 
Testing this one out.

**Comment by mfunk** [comment]
@topowright finding models are all corrupted for the 10.x tbx on this one per discussion yesterday. Going to have to rebuild them.

**Comment by mfunk** [comment]
@topowright 
.... should have clarified. These models need to be rebuilt... and so I am going to reject this PR in favor of a fix for whole toolbox.

**Pull request closed without merging**
