### PR TITLE
Merge for September 2017 release

### PR DESCRIPTION
**Pull request by mfunk**
September 2017 release items.

## Description
Fixes and enhancements in [September 2017 milestone](https://github.com/Esri/solutions-geoprocessing-toolbox/milestone/9)

## Related Issue
[September 2017 milestone](https://github.com/Esri/solutions-geoprocessing-toolbox/milestone/9)

## Motivation and Context
N/A

## How Has This Been Tested?
Automated tests.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by csmoore** [comment]
Running tests now - I never noticed this before but the Distance to Assets test do require you to have first logged on to ArcGISOnline - is this intentional/by design? Does this test work on the automated server?

This line/test driver is causing the issue: https://github.com/Esri/solutions-geoprocessing-toolbox/blob/dev/utils/test/distance_to_assets_tests/DistanceToAssetsCodeAssetsToBasesTestCase.py#L50

**Comment by csmoore** [comment]
(After removing DistanceToAssets tests) 

On ArcMap 10.3.1:

RESULTS =================================================
Number of tests run: 27
Number succeeded: 27
Number of errors: 0
Number of failures: 0
Number of tests skipped: 0
Percent passing: 100.0
=========================================================

Pro 1.4:

RESULTS =================================================
Number of tests run: 21
Number succeeded: 21
Number of errors: 0
Number of failures: 0
Number of tests skipped: 0
Percent passing: 100.0
=========================================================

**Comment by BobBooth** [comment]
@csmoore - I think you have to have local street network data and address locator to run Distance to Assets without being connected/signed in to AGOL.  @ACueva may be able to tell you where to get that local data to run tests.

**Comment by mfunk** [comment]
@csmoore 
Yes. The network service used to test the tools is on arcgis.com, and requires a login. I don't know all of the details of the tool but when I run the entire suite it pauses for me to login.

**Pull request merged**
