### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by pshowalter**
Modification to "Point of Origin Tools_10.3", tooldata, scripts, test_poo_tools.gdb, PointOfOrigin.py.  Temporarily removed an extra Pro Toolbox, until naming convention and folder structure is sorted out.

### CODE REVIEW

**Comment by mfunk** [comment]
@pshowalter did you upload the new geodatabase with **impact_pts_monterey_UTM10N** already?

**Comment by pshowalter** [comment]
@mfunk - It is in my local repo GDB, C:\myProjects\GitHub\solutions-geoprocessing-toolbox\capability\data\geodatabases\test_poo_tools.gdb\impact_pts_monterey_UTM10N.  Does that get included in the commit/sync processs?

**Comment by mfunk** [comment]
@pshowalter Nope. Test data are ignored by the commit/sync process ... intentionally. There is a separate process for downloading data for the tests. This is handled in the root *build.xml* file. Can you put the **impacts_pts_monterey_UTM10N** into a separate file geodatabase, ZIP it (don't package), and send it to me? Because there is an existing dataset to update I'll handle that part.

**Comment by pshowalter** [comment]
@mfunk - Is there a set of test scripts for Pro?

**Comment by mfunk** [comment]
No. I don't know if that is a limitation of ANT or if it is how the test harness was implemented. I haven't had a chance to take a further look into that. @csmoore or @ACueva might know though.

**Comment by csmoore** [comment]
Not a limitation of ant, but we do need to create an issue to change/test the scripts to also support Pro

**Pull request merged**
