### PR TITLE
Added APP6B to the Value list

### PR DESCRIPTION
**Pull request by topowright**
Added the APP6B to the value list for all tools inside the Miltiary Features toolbox.

## Description
APP6 support

Added APP6B to the value list for each tool in the Military Features Toolbox. 

## Related Issue

https://github.com/Esri/solutions-geoprocessing-toolbox/issues/418
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by csmoore** [comment]
Not sure if these are new, but I noticed a few issues: 

1. The tools in the converters folder did not have parameters updated:
 
image


2. Model broken:

image

**Comment by topowright** [comment]
@dfoll @ACueva  needs to be reviewed being that @csmoore is now out of the office

**Comment by topowright** [comment]
@dfoll reviewed this issue and can now be merged.

**Comment by csmoore** [comment]
I also had a look. It looks like this also addresses #418 

image

**Pull request merged**
