### PR TITLE
Update to POOD Toolbox

### PR DESCRIPTION
**Pull request by pshowalter**
??change toolbox script location.??

### CODE REVIEW

**Comment by nfeuerstein** [comment]
Are you asking a question, Patrick?

**Comment by pshowalter** [comment]
@mfunk Can you give me a few minutes of your time? I need to ensure that I am pulling upstream changes correctly and that this change is what I thought it was. Thanks!

**Comment by mfunk** [comment]
@pshowalter we don't want to change the paths to any scripts in the templates. In order for these tools to work they relative paths must be the same. Unless the path is somehow broken in the tool, then we fix it, but not to change it. That being said I don't see any broken paths in the tools now. What are you coming across?

**Comment by pshowalter** [comment]
I don't  have an intentional change to the Toolbox, so I clicked "Revert" in GitHub windows client.  I had noticed that that path shown in script tool was, showing the location on my local repo, so I thought that had changed, but the script tool is still set to "Store relative paths (instead of absolute paths)".  I see that I  examine the properties of the Point Of Origin Tools_10.3.tbx using ArcCatalog 10.3, the time stamp changes, even if you cancel.  So not sure why GH was indicating that it was a changed file.  
See next message for other issues when trying to refresh local repo.

**Comment by pshowalter** [comment]
Trying to update local repo produces the following:
patrick@PSHOWALTER2 /c/myProjects/GitHub/solutions-geoprocessing-toolbox (master)
$ git pull upstream master
From https://github.com/Esri/solutions-geoprocessing-toolbox
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        .gitmodules
        README.md
        data_management/README.md
        data_management/test/test_geonames_tools/TestCreateGeonamesGazetteerLocator.py
        data_management/toolboxes/CADRG ECRG Tools.pyt.xml
        data_management/toolboxes/CIB Tools.pyt.xml
        data_management/toolboxes/Elevation Tools.pyt.xml
        data_management/toolboxes/Geonames Tools_10.3.tbx
        data_management/toolboxes/scripts/CheckInput.py
        data_management/toolboxes/scripts/LoadGeonames.py
        patterns/README.md
        suitability/README.md
        suitability/toolboxes/Military Aspects of Terrain Tools.tbx
        suitability/toolboxes/Military Aspects of Terrain Tools_10.3.tbx
        visibility/README.md
Please, commit your changes or stash them before you can merge.
error: The following untracked working tree files would be overwritten by merge:
        patterns/toolboxes/Change Detection Tools.tbx
        patterns/toolboxes/Landsat Pre Processing Tools.tbx
Please move or remove them before you can merge.
Aborting

I am not working on any of the scripts, toolboxes, README's  mentioned, so not sure why it is indicating I have local changes.

**Comment by mfunk** [comment]
Since TBX files are binary, GitHub has no way of tracking changes other than file attributes (modify date, size, etc.). If you don't want to commit file changes you can 'Discard changes' in GitHub for Windows. Let me know if that doesn't make sense.

**Pull request closed without merging**
