### PR TITLE
Merging dev to master for v2.1.0

### PR DESCRIPTION
**Pull request by mfunk**

### CODE REVIEW

**Comment by mfunk** [comment]
Attempting to merge manually using above commands....but doesn't seem like anything really happened.
```
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox [Esri/master]> git checkout -b mfunk-master master
Switched to a new branch 'mfunk-master'
C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox [mfunk-master]> git pull https://github.com/mfunk/solutions-geoprocessing-toolbox.git master
From https://github.com/mfunk/solutions-geoprocessing-toolbox
 * branch            master     -> FETCH_HEAD
Already up-to-date.
C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox [mfunk-master]> git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox [master]> git merge --no-ff mfunk-master
Already up-to-date.
C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox [master]> git push origin master
Everything up-to-date
C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox [master]>
```

After sync, nothing happened in GH4W.
switch to Esri/master and there's a commit waiting to happen (659 files)
Try to commit and getting an error to commit for one, single file: operational_graphics/toolboxes/scripts/NumberFeatures.py. The one in this commit is the correct one. Need to force it somehow.

**Comment by csmoore** [comment]
To avoid using the git command line, you could have also just used the Github PR page to do a PR request to Esri\master from Esri\dev (assuming the changes you wanted to merge were there).  

You may also want to consider more frequent minor releases, 80+ commits & 650+ files is a lot of changes if you do encounter any issues/problems/conflicts.

**Comment by mfunk** [comment]
I hate the GH4W’s Pull Request page. I prefer to do it right from GH.com. As for the releases, I will probably be doing more of that once I figure out the “team-corrected procedures for releasing all items correctly” from Natalie, Lorraine, Ben, etc. I’m also still working out the kinks in building the ‘7 Zips from Hell’ that I use to release stuff to NSEC, which is where the real nastiness come in.

Anyway the real GH.com release is in draft and I wanted someone else to look at the Description and see if it seems reasonable for what we’ve got in the queue: https://github.com/Esri/solutions-geoprocessing-toolbox/releases/tag/untagged-71ac449910bab2fc9f7d. Would you give it a quick look and let me know any suggestions/corrections?

Thanks,
Matt

Matthew Funk
Esri  |  ArcGIS Solutions<http://solutions.arcgis.com/>

**Comment by csmoore** [comment]
Sorry - that's what I meant do a PR on Github.com from one branch to another in the same repo (or across repos). I've actually not seen the Github for Desktop one work (it always says "failed" when I have tried).

Release language looks good to me.  The only suggestion is for the issues reference rather than a date range, actually link to the milestone so the actually issues will be listed there: ex. https://github.com/Esri/solutions-geoprocessing-toolbox/milestones/Version%20-%20Next (or do this link after you rename the milestone with the release # - see next paragraph)

Speaking of Milestones/Releases, I did add a OneNote section "Github Releases" that attempts to layout a workflow to do this nicely (renaming the v.next milestone to release #, creating the release, etc.) so you may want to have a look at that to see if it is helpful.

**Comment by mfunk** [comment]
I will have to start doing that for the next release as we are effectively out of sync with the milestones listed. For this v2.1.0 we are actually covering the “Version – Next (Past due by 3 months)” and “Version – After Next (Due 10/30/2015)” milestones.

**Comment by csmoore** [comment]
You can also rearrange the issues/milestones to match reality before you do the release (move all of the completed ones into v.next and the incomplete ones in v.after next)

**Pull request merged**
