### PR TITLE
Fixed #594: error Number Features if field selected

### LINKED ISSUE #594: Number Features tool fails if I specify the existing Number field as the target field to number
Using the Clearing Operations solution sample data, if I run Number Features (from @mfunk mf-clrops-grg-framework branch) I am seeing the tool fail if I specify the Number field, but it works if I leave the input empty.

## Expected Behavior
Should number this field if it is specified.

## Steps to Reproduce (for bugs)
1. Open (ArcMap 10.3.1) the Clearing Operations solution
2. Connect to the toolbox
3. Run the Number Features tool.
4. Define an AOI around some or all of the features interactively.
5. Choose the "Numbered Structures Sample" layer as the features to number. This dataset has an Integer field called Number.
6. Leave Field to Number blank.
7. Leave output blank.
(INSERT EDITS BB)
The tool runs correctly.

8. Re-run, as before, but for step 6, change the Field to Number to use the "Number" field.
(END EDITS BB)
Tool will fail with:
Messages
Executing: NumberFeatures "Feature Set" "Results\Numbered Structures Sample" Number #
Start Time: Thu Sep 14 16:38:21 2017
Running script NumberFeatures...
outputFeatureClass: None
Shape type: Polygon
App environment: OTHER
Selecting points from <geoprocessing Layer object object at 0x0E3C7FC8> inside of the area in_memory\areaToNumber
Selected 15 points
Sorting the selected points geographically, left to right, top to bottom
Numbering the fields
Clearing the selection
Copying the features to the input, and then deleting the temporary feature class
PYTHON ERRORS:
Traceback info:
  File "C:\solutions-geoprocessing-toolbox-mf-clrops_Fix_Fix\solutions-geoprocessing-toolbox-mf-clrops-grg-framework\clearing_operations\scripts\NumberFeaturesTool.py", line 234, in NumberFeatures
    arcpy.AddMessage("what is the numberingField: " + numberingField)

Error Info:
cannot concatenate 'str' and 'geoprocessing value object' objects
ArcPy ERRORS:
Executing: SelectLayerByAttribute "<geoprocessing Layer object object at 0x0E3C7FC8>" CLEAR_SELECTION #
Start Time: Thu Sep 14 16:38:23 2017
Succeeded at Thu Sep 14 16:38:23 2017 (Elapsed Time: 0.00 seconds)

Completed script NumberFeatures...
Failed to execute (NumberFeatures).
Failed at Thu Sep 14 16:38:23 2017 (Elapsed Time: 1.46 seconds)

## Context
This causes an impediment for the Clearing Operations solution release.

## Your Environment
ArcMap 10.3.1
Clearing Operations Solution (from staging)
Tool from the current (mfunk mf-clrops-grg-framework) branch of the repo.

### PR DESCRIPTION
**Pull request by mfunk**
Fixed #594

## Description
Convert gp field object to string representation of object.

## Related Issue
#594

## Motivation and Context
fix bug

## How Has This Been Tested?
manual and automated tests passing.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by mfunk** [comment]
@BobBooth 
please check if this fixes the problem on your end.

**Comment by BobBooth** [comment]
@mfunk - yes, this does fix the problem.

**Comment by mfunk** [comment]
@BobBooth Can you do a review and approve? (can't merge without one)

**Comment by BobBooth** [comment]
@mfunk - reviewed yesterday, see comment above.  Didn't do the GitHub R/A workflow, sorry. Should be good to go now.

**Comment by mfunk** [comment]
As long as he can Review then I'll do the merge.....guess it's already done. But I can't merge without an Review with Approve.

**Pull request merged**
