### PR TITLE
Distance To Assets updates

### PR DESCRIPTION
**Pull request by mfunk**
- Renamed _pro with spaces
- Added Descriptions to both toolboxes
- Added same Alias to both toolboxes
- Added missing .LYR and .LYRX to layers folder.

## Description
see above...

## Related Issue
None

## Motivation and Context
Make sure toolboxes follow guidelines for toolboxes.
Missing symbology for tool outputs.

## How Has This Been Tested?
Manual test.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by mfunk** [comment]
@csmoore Hold off on reviewing this one still finding issues with the toolboxes/tools. Will update them soon.

**Comment by mfunk** [comment]
@csmoore Was finding that the some of the defaults were pointing to local hardcoded paths. They should be ready to go.

**Comment by csmoore** [comment]
Looked at tools in PR, described changes above, and [issue](https://github.com/ArcGIS/solutions-desktop-templates/issues/404) - I don't have the data to run the tools, but things looks as described above and issue with default parameters seems addressed:

image

image

image

**Comment by adgiles** [comment]
@mfunk the geocoder wants to be a hard coded path, otherwise the user is going to have to know the URL to the online world geocode service

**Comment by csmoore** [comment]
@adgiles - that still seemed to work - but you may want to grab the latest to confirm since you may be more familiar with the tools

**Comment by mfunk** [comment]
@adgiles 
In Pro the geocoder is set to a URL so I left it alone:
image


In Desktop though it pointed to "D:\streemap_na\data\Street_Addresses_US" which is a path that does not exist on most machines. So that one got removed:
image

**Comment by adgiles** [comment]
can we point the desktop to the same on as Pro?

**Comment by mfunk** [comment]
@adgiles 
I get an error in the Input Address Locator parameter for the **Geocode Asset Address Fields** with the path: *https://geocode.arcgis.com/arcgis/rest/services/World\GeocodeServer*:

image

I don't have this error in Pro.

**Comment by adgiles** [comment]
ok, it must have to be set by adding a geocode service to the server connects in catalog, which is documented in the help. So probably best just to leave it blank like you have done

**Comment by mfunk** [comment]
@adgiles Will do. Tried a few variations of inputs but got nowhere. Not sure if there was some combination of url/login/token that might have worked but no luck.

**Pull request merged**
